enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-version = "v3.15.0-dev.7"
cli-source = "inotia00/revanced-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#Stock Icon

[AnddeaYouTubeRVXAPK]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"

[AnddeaYouTubeMusicRVXAPK]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom header for YouTube Music' "

# MMT Icon

[AnddeaYouTubeRVXAPK_MMT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_MMT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_MMT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=mmt -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_MMT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=mmt -e 'Custom header for YouTube Music' "

# MMT Blue Icon

[AnddeaYouTubeRVXAPK_MMTB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt_blue -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_MMTB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt_blue -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_MMTB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=mmt_blue -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_MMTB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=mmt_blue -e 'Custom header for YouTube Music' "

# Revancify Blue Icon

[AnddeaYouTubeRVXAPK_REVB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_blue -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_REVB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_blue -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_REVB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=revancify_blue -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_REVB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=revancify_blue -e 'Custom header for YouTube Music' "

# Revancify Red Icon

[AnddeaYouTubeRVXAPK_REVR]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_red -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_REVR]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_red -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_REVR]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=revancify_red -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_REVR]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=revancify_red -e 'Custom header for YouTube Music' "

# Vanced Black Icon

[AnddeaYouTubeRVXAPK_VNCDB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=vanced_black -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_VNCDB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=vanced_black -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_VNCDB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=vanced_black -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_VNCDB]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=vanced_black -e 'Custom header for YouTube Music' "

# Vanced Light Icon

[AnddeaYouTubeRVXAPK_VNCDL]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=vanced_light -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_VNCDL]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=vanced_light -e 'Custom header for YouTube' "

[AnddeaYouTubeMusicRVXAPK_VNCDL]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "apk"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=vanced_light -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule_VNCDL]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "both"
build-mode = "module"
version = "8.30.54"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=vanced_light -e 'Custom header for YouTube Music' "

# YouTube Black Icon

[AnddeaYouTubeRVXAPK_BLACK]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "apk"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=youtube_black -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule_BLACK]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
version = "20.21.37"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=youtube_black -e 'Custom header for YouTube' "
